[build]
  publish = "Avumile Tati Portfolio"
  command = "npm install"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

